os: Visual Studio 2015

version: 1.1.{build}-pre
environment:
    COVERALLS_REPO_TOKEN:  
       secure: 8JYxwCWszeAaWBr41pD17LB925K7Sk7utvKsIb1qz44i2anf9uLmvh2q0ilMQTBO

cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

before_build:
  - nuget restore src/Halcyon.sln

configuration: Release

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
  
install:
- dnvm upgrade -r clr
- dnu restore

build:
  verbosity: minimal
  project: src\Halcyon.sln
  publish_nuget: true             # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: true     # generate and publish NuGet symbol packages

after_test: 
    - src\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -filter:"+[Halcyon*]* -[Halcyon.Tests]*" -target:"src\packages\xunit.runner.console.2.1.0\tools\xunit.console.exe" -targetargs:"src\Halcyon.Tests\bin\Release\Halcyon.Tests.dll -appveyor -noshadow" -output:coverage.xml
    - src\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover -f -r %COVERALLS_REPO_TOKEN% coverage.xml

deploy:
  provider: NuGet
  api_key:
    secure: +AIEY0E9rURDXqzW7YM/RoRXDhOxdTZQ4XyUxNCKR6zaHvj7ha/uZHnhqofdaUu3
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
   branch: master